baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.47"
